[package]
name = 'bls'
version = '0.1.0'
authors = ['Paul Hauner <paul@paulhauner.com>']
edition = '2018'

[dependencies]
milagro_bls = { git = 'https://github.com/sigp/milagro_bls', tag = 'v0.11.1' }
eth2_hashing = '0.1.0'
hex = '0.3'
rand = '0.7.2'
serde = '1.0.102'
serde_derive = '1.0.102'
serde_hex = '0.1.0'
ssz_new = { path = '../ssz_new' }
eth2_ssz_types = '0.2.0'
tree_hash = '0.1.0'

[features]
fake_crypto = []
