#[derive(PartialEq, Debug)]
pub enum Error {
    SlotOutOfRange,
    IndexOutOfRange,
    CustodyBit1Set,
    CustodyBitIndicesNotSorted,
    CustodyBitIndicesIntersect,
    IndicesExceedMaxValidators,
    InvalidSignature,
    NumberExceedsCapacity,
    ArrayIsEmpty,
    NotAHash,
    ConversionToUsize,
    ConversionToVariableList,
    AttestationBitsInvalid,
    MaxIndicesExceeded,
    BadValidatorIndicesOrdering,
    ValidatorExitAlreadyInitiated,
    DecodeError,
}
